In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv('Dataset/cause_of_deaths.csv')

In [3]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6120 entries, 0 to 6119
Data columns (total 34 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country/Territory                           6120 non-null   object
 1   Code                                        6120 non-null   object
 2   Year                                        6120 non-null   int64
 3   Meningitis                                  6120 non-null   int64
 4   Alzheimer's Disease and Other Dementias     6120 non-null   int64
 5   Parkinson's Disease                         6120 non-null   int64
 6   Nutritional Deficiencies                    6120 non-null   int64
 7   Malaria                                     6120 non-null   int64
 8   Drowning                                    6120 non-null   int64
 9   Interpersonal Violence                      6120 non-null   int64
 10  Maternal Disorders                          6120 non-null   int64
 11  HIV/AIDS                                    6120 non-null   int64
 12  Drug Use Disorders                          6120 non-null   int64
 13  Tuberculosis                                6120 non-null   int64
 14  Cardiovascular Diseases                     6120 non-null   int64
 15  Lower Respiratory Infections                6120 non-null   int64
 16  Neonatal Disorders                          6120 non-null   int64
 17  Alcohol Use Disorders                       6120 non-null   int64
 18  Self-harm                                   6120 non-null   int64
 19  Exposure to Forces of Nature                6120 non-null   int64
 20  Diarrheal Diseases                          6120 non-null   int64
 21  Environmental Heat and Cold Exposure        6120 non-null   int64
 22  Neoplasms                                   6120 non-null   int64
 23  Conflict and Terrorism                      6120 non-null   int64
 24  Diabetes Mellitus                           6120 non-null   int64
 25  Chronic Kidney Disease                      6120 non-null   int64
 26  Poisonings                                  6120 non-null   int64
 27  Protein-Energy Malnutrition                 6120 non-null   int64
 28  Road Injuries                               6120 non-null   int64
 29  Chronic Respiratory Diseases                6120 non-null   int64
 30  Cirrhosis and Other Chronic Liver Diseases  6120 non-null   int64
 31  Digestive Diseases                          6120 non-null   int64
 32  Fire, Heat, and Hot Substances              6120 non-null   int64
 33  Acute Hepatitis                             6120 non-null   int64
dtypes: int64(32), object(2)
memory usage: 1.6+ MB

In [4]:
raw_data.head()

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,2195,3862,425,2797,5681,6445,2943,5568,396,3601
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,2231,3932,451,3038,6001,6664,3027,5739,420,3816

In [10]:
data1 = raw_data.groupby(['Country/Territory']).sum()

/tmp/ipykernel_44786/3730879266.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data1 = raw_data.groupby(['Country/Territory']).sum()

In [14]:
data1.drop(['Year'], axis=1)

,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,Maternal Disorders,HIV/AIDS,Drug Use Disorders,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
Country/Territory,,,,,,,,,,,,,,,,,,,,,
Afghanistan,78666,41998,13397,71453,13924,56536,108228,129621,4282,7094,...,93207,134676,14530,70163,208331,209857,98419,186959,13559,98108
Albania,1323,16549,4491,569,0,2397,5242,246,57,634,...,4055,7636,500,526,8522,22632,8717,14907,636,44
Algeria,15685,86914,22943,7138,70,24273,16702,29475,6101,10612,...,89035,154666,12337,6407,369395,168453,91927,146527,27628,10492
American Samoa,30,143,69,60,0,120,101,30,15,0,...,970,512,0,60,164,612,181,341,0,0
Andorra,0,614,137,0,0,0,15,0,85,0,...,198,292,0,0,259,838,283,560,0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,11615,108735,18573,22554,3726,20273,266071,12739,46090,1664,...,175790,161667,2607,21347,175036,122198,91720,168365,4949,1109
Vietnam,38559,369363,83322,48613,17311,214356,47981,13167,148838,19959,...,544222,396874,34681,7366,594980,911787,527192,735817,17380,30650
Yemen,21095,31045,7188,68939,143463,27994,17918,53611,6276,3718,...,30812,52119,12561,66731,278327,126525,64136,111536,23871,26532
Zambia,98886,13473,4054,95913,205529,12809,30065,28395,1175563,933,...,54098,41751,9056,92915,56976,59173,100581,147640,9476,8846
Zimbabwe,41238,20017,5764,66723,118728,18169,32741,29802,1836042,2271,...,71175,49952,9113,65942,67207,71774,55027,108691,14718,3778

In [15]:
import matplotlib.pyplot as plt

In [17]:
plt.pie(data1['Afghanistan'])

KeyError: 'Afghanistan'